Repository gisce/gestionatr, pull requests merged in 2018-09, with the labels that each got.

#76 IMP R1: import cases whith "<VariablesDetalleReclamacion/>"
  gestionatr/input/messages/R1.py
Labels: bug, enhancement

#77 Suport for process A1_44
  gestionatr/defs_gas.py
  gestionatr/input/messages/A1_44.py
  gestionatr/input/messages/__init__.py
  gestionatr/input/messages/message_gas.py
  gestionatr/output/messages/sw_a1_05.py
  gestionatr/output/messages/sw_a1_44.py
  tests/data/a144.xml
  tests/data/a244.xml
  tests/data/a344.xml
  tests/data/a444.xml
  tests/test_input.py
  tests/test_output.py
Labels: enhancement

#80 Añadir parametro en `get_contracted_periods_by_period` para utilizar la facturada
  gestionatr/input/messages/F1.py
Labels: enhancement

#78 Suport for process A1_04
  gestionatr/input/messages/A1_04.py
  gestionatr/input/messages/__init__.py
  gestionatr/input/messages/message_gas.py
  gestionatr/output/messages/sw_a1_04.py
  tests/data/a104.xml
  tests/data/a204.xml
  tests/data/a304.xml
  tests/data/a404.xml
  tests/test_input.py
  tests/test_output.py
Labels: To be merged, enhancement

#82 Soporte para proceso A1_48: Reclamaciones de gas
  gestionatr/input/messages/A1_48.py
  gestionatr/input/messages/__init__.py
  gestionatr/input/messages/message_gas.py
  gestionatr/output/messages/sw_a1_48.py
  tests/data/a148.xml
  tests/data/a248.xml
  tests/data/a2548.xml
  tests/data/a2648.xml
  tests/data/a348.xml
  tests/test_input.py
  tests/test_output.py
Labels: WIP
