Repository gisce/gestionatr, pull requests merged in 2021-08, with the labels that each got.

#172 CAMBIOS EN FORMATOS: V2.1.1 DE GAS NATURAL
  gestionatr/data/A105.xsd
  gestionatr/data/A205.xsd
  gestionatr/data/A305.xsd
  gestionatr/data/CommonTagsCONT.xsd
  gestionatr/defs_gas.py
Labels: enhancement, WIP

#174 Fixes excesos de potencia herencia de periodo
  gestionatr/input/messages/F1.py
Labels: enhancement, To be merged

#177 ATR 2.2 de electricidad para información al consumidor y maxímetros año móvil
  gestionatr/data/Facturacion.xsd
  gestionatr/data/SaldoLecturasFacturacion.xsd
  gestionatr/data/TiposComplejos.xsd
  gestionatr/data/TiposSencillos.xsd
  gestionatr/input/messages/F1.py
  gestionatr/output/messages/sw_f1.py
  tests/data/f101_factura_atr.xml
  tests/data/f101_factura_atr_direccion_suministro.xml
  tests/data/f101_factura_atr_medidas_baja.xml
  tests/test_input.py
  tests/test_output.py
Labels: enhancement, To be merged

#183 FIX cálculo de maxímtros consumidor como float
  gestionatr/input/messages/F1.py
Labels: bug, To be merged
