Repository gisce/gestionatr, pull requests merged in 2022-01, with the labels that each got.

#192 Minor fixes
  gestionatr/input/messages/F1.py
Labels: bug, To be merged

#193 Recuperar el tipo de punto de medida del F1
  gestionatr/input/messages/F1.py
Labels: enhancement, To be merged

#196 Substituir travis por gihub actions
  .github/workflows/python-app.yml
  .github/workflows/python-publish.yml
  .travis.yml
Labels: To be merged
