Repository gisce/gestionatr, pull requests merged in 2022-05, with the labels that each got.

#206 Try to import Rechazo
  gestionatr/cli.py
Labels: bug

#207 Allow to create P0 from CLI params
  gestionatr/cli.py
Labels: enhancement

#199 IMP añade posibilidad que la distribuidora envie coeficientes 0 para autoconsumo colectivo
  gestionatr/input/messages/F1.py
Labels: enhancement, To be merged
