Repository gisce/gestionatr, pull requests merged in 2024-12, with the labels that each got.

#265 Corrección temporal de ATR 2.6 a la espera de aprovación de Orden de la CNMC y del ministerio para GAS
  gestionatr/data/A1225.xsd
  gestionatr/data/A1239.xsd
  gestionatr/data/A1350.xsd
  gestionatr/data/A138.xsd
  gestionatr/data/A1550.xsd
  gestionatr/data/A302.xsd
  gestionatr/data/A338.xsd
  gestionatr/data/A341.xsd
  gestionatr/data/A342.xsd
Labels: patch

#264 Permitir decidir si cuadrar ajustes al obtener lecturas
  gestionatr/input/messages/F1.py
Labels: enhancement, minor, deployed PRE

#266 Fix tfx demandat
  gestionatr/input/messages/B70.py
Labels: minor, patch

#267 FIX 2009 tipus
  gestionatr/defs_gas.py
Labels: minor, patch

#268 FEAT: Add exception type on except_F1 exception to decide which to send to Sentry
  gestionatr/input/messages/message.py
Labels: minor
