Repository gisce/gestionatr, pull requests merged in 2024-11, with the labels that each got.

#259 Si lectura tiene un motivo de ajuste no se sobreescribe si tiene ajuste con decimales
  gestionatr/input/messages/F1.py
Labels: bug, To be merged

#261 Permitir obtener lecturas del F1 si el CG tiene mas periodos que la tarifa del contrato
  gestionatr/input/messages/F1.py
Labels: enhancement, To be merged, patch

#263 #MDG
  .bumpversion.cfg
Labels: patch, CI
