Repository gisce/gestionatr, pull requests merged in 2024-09, with the labels that each got.

#253 check if there is pcs before division
  gestionatr/input/messages/B70.py
Labels: bug, To be merged

#254 Comprovar que tenemos todas las variables, para prevenir division por 0
  gestionatr/input/messages/B70.py
Labels: bug, To be merged, patch

#255 Fix: add A2S02 Support
  gestionatr/input/messages/message_gas.py
Labels: bug, minor

#256 Fix: add A2S02 Support
  gestionatr/input/messages/message_gas.py
Labels: bug, patch

#249 Habilitar Q1
  gestionatr/input/messages/Q1.py
  tests/test_input.py
Labels: enhancement, minor
