Repository gisce/gestionatr, pull requests merged in 2025-05, with the labels that each got.

#272 Asignar precios de cargos correctamente cuando esten agrupados
  gestionatr/input/messages/F1.py
Labels: To be merged, patch, deployed PRE

#273 Corregir importación de F1s con lecturas totalizadoras código 90 y A0
  gestionatr/input/messages/F1.py
Labels: bug, To be merged

#274 Desactivar detección de periodos agrupados para tarifas 3.0A (deprecated)
  gestionatr/input/messages/F1.py
Labels: bug, To be merged, patch
